---
- name: mysql_secure
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
  action: mysql_user user="" state="absent"
  action: mysql_db db=test state=absent
  action: mysql_user login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
              - "{{ ansible_hostname }}"
              - 127.0.0.1
              - ::1
              - localhost
  action: file path=/root/.my.cnf state=absent
